# LCD Project
TOP_MODULE = lcd_controller
SYNTH_SOURCES += ../provided_modules/inv.sv
SYNTH_SOURCES += ../provided_modules/dff.sv
SYNTH_SOURCES += $(TOP_MODULE).sv
-include ../simulation.mk
-include ../fpga.mk

